apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mysql-operator
rules:
  # Доступ к объектам MySQL
  - apiGroups:
      - "otus.homework"
    resources:
      - mysqls
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete

  # Доступ к деплоям, сервисам, PV / PVC
  - apiGroups:
      - ""
    resources:
      - services
      - persistentvolumes
      - persistentvolumeclaims
      - pods
    verbs:
      - "*"

  - apiGroups:
      - "apps"
    resources:
      - deployments
    verbs:
      - "*"