apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-operator
  template:
    metadata:
      labels:
        app: mysql-operator
    spec:
      serviceAccountName: mysql-operator
      containers:
        - name: operator
          image: roflmaoinmysoul/mysql-operator:1.0.0
          imagePullPolicy: Always

      # Для использованеия образа созданного в рамках задания с ** закоментировать прошлое описание контейнера и раскоментировать то что ниже

        # - name: operator
        #   image: mysql-operator:1.0.0
        #   imagePullPolicy: Never