apiVersion: v1
kind: Service
metadata:
  name: homework3-service
  namespace: homework
spec:
  selector:
    app: homework-2-app
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000